/*
 * Copyright (c) 2022 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * @addtogroup power
 * @{
 *
 * @brief Provides APIs for performing hibernation/wakeup operations, subscribing to the hibernation/wakeup status,
 * and managing running locks.
 * 
 * After obtaining an object or proxy of this module, the power service can invoke related APIs to perform
 * hibernation/wakeup operations, subscribe to the hibernation/wakeup status, and manage running locks.
 *
 * @since 3.1
 * @version 1.0
 */

 /**
 * @file IPowerHdiCallback.idl
 *
 * @brief Provides the callbacks of the hibernation/wakeup status.
 *
 * The power module provides callbacks for the power service to obtain the hibernation/wakeup status.
 *
 * @since 3.1
 * @version 1.0
 */

package ohos.hdi.power.v1_0;

/**
 * @brief Represents the callbacks of the hibernation/wakeup status.
 *
 * After creating a callback object, the power service can call {@link IPowerInterface} to register a callback to
 * subscribe to hibernation/wakeup status changes.
 *
 * @since 3.1
 */
[callback] interface IPowerHdiCallback {
    /**
     * @brief Callback of the hibernation state.
     *
     * This callback is used to notify the power service when the device enters the hibernation state.
     *
     * @since 3.1
     */
    OnSuspend();

    /**
     * @brief Callback of the wakeup state.
     *
     * This callback is used to notify the power service when the device enters the wakeup state.
     *
     * @since 3.1
     */
    OnWakeup();
}
/** @} */
