/*
 * Copyright (c) 2022 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * @addtogroup thermal
 * @{
 *
 * @brief Provides APIs for managing, controlling, and subscribing to the device temperature.
 * 
 * After obtaining an object or proxy of this module, the thermal service can invoke related APIs to manage, control,
 * and subscribe to the device temperature.
 *
 * @since 3.1
 * @version 1.0
 */

/**
 * @file ThermalTypes.idl
 *
 * @brief Enumerates data types related to thermal management.
 *
 * Such data types include thermal information and thermal information list.
 *
 * @since 3.1
 * @version 1.0
 */

package ohos.hdi.thermal.v1_0;

/**
 * @brief Defines the device thermal information.
 *
 * @since 3.1
 */
struct ThermalZoneInfo {
    /** Device type */
    String type;
    /** Device temperature */
    int temp;
};

/**
 * @brief Defines the device thermal information list.
 *
 * @since 3.1
 */
struct HdfThermalCallbackInfo {
    /** Device thermal information list */
    List<struct ThermalZoneInfo> info;
};
/** @} */
