/*
 * Copyright (c) 2022 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package ohos.hdi.memorytracker.v1_0;

import ohos.hdi.memorytracker.v1_0.MemoryTrackerTypes;

interface IMemoryTrackerInterface {
    /**
     * @brief Get the memory record with specified type.
     *
     * @param pid Indicates the process id. If pid equals to 0, it means to get memory records of all processes.
     * @param type Indicates type of device.
     * @param records Indicates the list of memory record.
     *
     * @return Returns <b>0</b> if the operation is successful.
     * @return Returns a negative value if the operation fails.
     *
     * @since 3.2
     */
    GetDevMem([in] int pid, [in] enum MemoryTrackerType type, [out] struct MemoryRecord[] records);
}